background_cam:
  ros__parameters:
    video_device: "/dev/video2"  # Adjust to match your USB camera device
    image_width: 640
    image_height: 480
    pixel_format: "yuyv"
    camera_frame_id: "background_cam"